/**
 * LEARNING HUB UPDATE ZONE
 *
 * 课程卡片、推荐列表和课程详情页都读取本文件。
 * 后续可将 Excel 的 Courses / Replays 工作表批量转换为这里的数据。
 */
window.LEARNING_HUB_CONTENT = Object.freeze({
  updatedAt: "2026-08-27",

  courses: [
    {
      id: "code-of-conduct-2026-q3",
      type: "essential",
      title: "2026 Q3 Code of Conduct Annual Refresh",
      titleZh: "2026 年第三季度行为准则年度复训",
      topic: "Compliance",
      summary: "完成年度行为准则必修内容，并在截止日期前确认学习记录。",
      description: "本课程帮助员工回顾公司行为准则、利益冲突、信息保护与合规决策的核心要求，并通过企业情境练习确认理解。",
      learningOutcomes: ["识别常见合规风险与升级路径", "理解利益冲突和信息保护要求", "完成年度知识确认并保留学习记录"],
      audience: "All employees",
      instructor: "Ethics & Compliance Team",
      dueDate: "2026-09-30T23:59:00+08:00",
      startDate: "",
      endDate: "",
      registrationDeadline: "",
      format: "Self-paced · LMS",
      location: "Online",
      language: "中文 / English",
      status: "Action required",
      totalSeats: null,
      seatsLeft: null,
      actionUrl: "",
      recommended: false,
      isActive: true,
      sortOrder: 1,
    },
    {
      id: "data-privacy-essentials-2026",
      type: "essential",
      title: "Data Privacy Essentials 2026",
      titleZh: "2026 数据隐私基础必修课",
      topic: "Compliance",
      summary: "掌握个人信息、敏感数据和跨团队共享中的基本保护要求。",
      description: "围绕员工日常工作中的数据收集、存储、分享与删除场景，说明如何判断个人信息和敏感信息，并采取正确的保护措施。",
      learningOutcomes: ["区分个人信息与敏感信息", "在共享和存储数据时选择合适的保护方式", "发现风险时使用正确的报告渠道"],
      audience: "Employees handling business or personal data",
      instructor: "Data Privacy Office",
      dueDate: "2026-10-15T23:59:00+08:00",
      startDate: "",
      endDate: "",
      registrationDeadline: "",
      format: "Self-paced · LMS",
      location: "Online",
      language: "中文 / English",
      status: "Required",
      totalSeats: null,
      seatsLeft: null,
      actionUrl: "",
      recommended: false,
      isActive: true,
      sortOrder: 2,
    },
    {
      id: "root-cause-analysis-workshop",
      type: "upcoming",
      title: "Root Cause Analysis Workshop",
      titleZh: "根因分析实战工作坊",
      topic: "Quality",
      summary: "使用结构化工具从问题表象走向可验证的根因和改进行动。",
      description: "通过真实业务案例练习问题陈述、证据收集、原因分析和对策验证。课程包含小组演练，适合正在参与偏差处理、质量改善或问题解决项目的员工。",
      learningOutcomes: ["写出清晰且可验证的问题陈述", "选择合适的根因分析工具", "把分析结论转化为可跟踪的改进行动"],
      audience: "Quality, Operations and Engineering teams",
      instructor: "Linda Wang",
      dueDate: "",
      startDate: "2026-09-04T09:30:00+08:00",
      endDate: "2026-09-04T16:30:00+08:00",
      registrationDeadline: "2026-09-02T18:00:00+08:00",
      format: "On-site",
      location: "Shanghai Training Center",
      language: "中文",
      status: "报名中",
      totalSeats: 30,
      seatsLeft: 14,
      actionUrl: "",
      recommended: true,
      isActive: true,
      sortOrder: 1,
    },
    {
      id: "influencing-without-authority",
      type: "upcoming",
      title: "Influencing Without Authority",
      titleZh: "无职权影响力",
      topic: "Leadership",
      summary: "在没有直接汇报关系的情况下建立共识并推动跨团队行动。",
      description: "课程聚焦利益相关方分析、影响策略和关键对话，通过案例演练帮助学员在矩阵组织中更有效地推进合作。",
      learningOutcomes: ["识别关键利益相关方的关注点", "选择适合情境的影响策略", "设计一场推动共识的关键对话"],
      audience: "Project leads and cross-functional contributors",
      instructor: "Alex Liu",
      dueDate: "",
      startDate: "2026-09-10T14:00:00+08:00",
      endDate: "2026-09-10T16:30:00+08:00",
      registrationDeadline: "2026-09-08T18:00:00+08:00",
      format: "Teams Live",
      location: "Online",
      language: "English",
      status: "席位有限",
      totalSeats: 25,
      seatsLeft: 6,
      actionUrl: "",
      recommended: true,
      isActive: true,
      sortOrder: 2,
    },
    {
      id: "power-bi-practical-lab",
      type: "upcoming",
      title: "Power BI Practical Lab",
      titleZh: "Power BI 数据分析实践",
      topic: "Digital",
      summary: "从业务数据出发完成清洗、建模和交互式看板制作。",
      description: "在讲师引导下完成一个端到端 Power BI 小项目，重点练习数据准备、指标设计、可视化选择和业务结论表达。",
      learningOutcomes: ["完成基础数据清洗与模型关系设置", "构建核心业务指标", "设计可支持决策的交互式看板"],
      audience: "Employees with basic Excel skills",
      instructor: "Chen Zhou",
      dueDate: "",
      startDate: "2026-09-18T13:30:00+08:00",
      endDate: "2026-09-18T17:00:00+08:00",
      registrationDeadline: "2026-09-15T18:00:00+08:00",
      format: "Hybrid",
      location: "Wuxi / Teams",
      language: "双语",
      status: "开放候补",
      totalSeats: 24,
      seatsLeft: 0,
      actionUrl: "",
      recommended: false,
      isActive: true,
      sortOrder: 3,
    },
    {
      id: "daily-management-system-essentials",
      type: "upcoming",
      title: "Daily Management System Essentials",
      titleZh: "日常管理系统基础",
      topic: "Operations",
      summary: "建立可视化、分层会议和问题升级组成的日常管理节奏。",
      description: "课程介绍 Daily Management System 的基本结构，并通过团队节奏设计练习帮助管理者把目标、异常和改进行动连接起来。",
      learningOutcomes: ["理解日常管理系统的核心组成", "设计适合团队的分层会议节奏", "建立问题升级和行动跟踪机制"],
      audience: "Team leaders and operations supervisors",
      instructor: "May Yang",
      dueDate: "",
      startDate: "2026-09-24T10:00:00+08:00",
      endDate: "2026-09-24T12:00:00+08:00",
      registrationDeadline: "2026-09-22T18:00:00+08:00",
      format: "Teams Live",
      location: "Online",
      language: "中文",
      status: "报名中",
      totalSeats: 40,
      seatsLeft: 22,
      actionUrl: "",
      recommended: true,
      isActive: true,
      sortOrder: 4,
    },
  ],

  replays: [
    { id: "quality-culture-speaker-series", title: "Quality Culture Speaker Series", titleZh: "质量文化系列分享", sessionDate: "2026-07-24T14:00:00+08:00", speaker: "Linda Wang", duration: "52 min", topic: "Quality", url: "", isActive: true, sortOrder: 1 },
    { id: "tell-better-stories-with-data", title: "Tell Better Stories with Data", titleZh: "用数据讲出更有影响力的故事", sessionDate: "2026-07-16T10:00:00+08:00", speaker: "Chen Zhou", duration: "68 min", topic: "Digital", url: "", isActive: true, sortOrder: 2 },
    { id: "coaching-conversations-for-managers", title: "Coaching Conversations for Managers", titleZh: "管理者教练式对话", sessionDate: "2026-06-30T15:00:00+08:00", speaker: "Alex Liu", duration: "74 min", topic: "Leadership", url: "", isActive: true, sortOrder: 3 },
    { id: "a3-thinking-in-daily-operations", title: "A3 Thinking in Daily Operations", titleZh: "日常运营中的 A3 思维", sessionDate: "2026-06-18T13:30:00+08:00", speaker: "May Yang", duration: "61 min", topic: "Operations", url: "", isActive: true, sortOrder: 4 },
  ],
});
